#include <iostream>
#include <functional>
#include <unordered_set>
#include <unordered_map>
#include <algorithm>
#include <assert.h>
#include <climits>
#include <cstring>
#include <numeric>
#include <iomanip>
#include <vector>
#include <string>
#include <bitset>
#include <array>
#include <cmath>
#include <queue>
#include <stack>
#include <tuple>
#include <deque>
#include <set>
#include <map>

#define fi first 
#define se second 
#define pb push_back
#define pf push_front
#define ppb pop_back
#define ppf pop_front
#define ld long double
#define ll long long int
#define Int unsigned int 
#define Long unsigned long long int
#define eliminate(x, y) (x).erase(remove(all(x), (y)), (x).end())
#define make_unique(x) sort(all(x)), (x).erase(unique(all(x)), (x).end());
#define all_range(x) (x).begin(), (x).begin()
#define All(x) (x).rbegin(), (x).rend()
#define all(x) (x).begin(), (x).end()
#define sz(x) (int)x.size()
#define newl cerr << '\n'

using namespace std;
template<class T> using Set = unordered_set<T>;
template<class T> using min_heap = priority_queue<T, vector<T>, greater<T>>;  
template<class T, class U> using Map = unordered_map<T, U>;
 
template<typename T>void prd(const T& x);
template<typename T, typename U>void prd(const pair<T, U>& val);
template<typename T, typename... Args>void prd(const T& val, Args... args);
template<typename... Args>void debug(Args... args);
template<typename T>void debug(const set<T>& c);
template<typename T>void debug(const vector<T>& c);
template<typename T>void debug(const vector<vector<T>> &c);
template<typename K, typename V>void debug(const map<K, V>& c);

const int MOD = 1e9 + 7;
const int mod = 998244353;
const int INF = 2e9 + 7;
const ll INFL = 9e18 + 7;
const double EPS = 1e-9;

void FastIO();

const int N = 3e5 + 9;
const int MAXN = 2e7 + 10;
const int MAX_PRIMES = 2e6 + 10;
const int PHI_N = 1e5;
const int PHI_K = 100;

struct PrimeCount {
    int cnt = 0; // total number of primes generated by sieve
    int primes[MAX_PRIMES];
    int pref[MAXN]; // pref[i] --> number of primes <= i
    int dp[PHI_N][PHI_K]; // precal of calc(n,k)
    bitset<MAXN> f;

    PrimeCount() {
        f[1] = true;
        for(int i = 4; i < MAXN; i += 2)
            f[i] = true;

        for(int i = 3; i * i < MAXN; i += 2) if(!f[i])
            for(int j = i * i; j < MAXN; j += i << 1)
                f[j] = true;

        for(int i = 1; i < MAXN; i++){
            if(!f[i]) primes[cnt++] = i;
            pref[i] = cnt;
        }

        for(int n = 0; n < PHI_N; n++) 
            dp[n][0] = n;

        for(int k = 1; k < PHI_K; k++)
            for(int n = 0; n < PHI_N; n++) 
                dp[n][k] = dp[n][k - 1] - dp[n / primes[k - 1]][k - 1];
    }

    // returns the number of integers less or equal n which are
    // not divisible by any of the first k primes
    // recurrence --> calc(n, k) = calc(n, k-1) - calc(n / p_k , k-1)
    // for sum of primes calc(n, k) = calc(n, k-1) - p_k * calc(n / p_k , k-1)
    ll calc(ll n, int k) {
        if(n < PHI_N && k < PHI_K) return dp[n][k];
        if(k == 1) return ((++n) >> 1);
        if(primes[k - 1] >= n) return 1;
        return calc(n, k - 1) - calc(n / primes[k - 1], k - 1);
    }
    // O( n^(2/3).(log n^(1/3)) )
    ll Legendre(ll n) {
        if(n < MAXN) return pref[n];
        int lim = sqrt(n) + 1;
        int k = upper_bound(primes, primes + cnt, lim) - primes;
        return calc(n, k) + (k - 1);
    }

    ll operator()(ll n) {
        return prime_count(n);
    }
    // runs under 0.2s for n = 1e12
    ll prime_count(ll n) {
        if(n < MAXN) return pref[n];

        ll w, res = 0;
        int b = sqrt(n), c = prime_count(cbrt(n)), a = prime_count(sqrt(b)); 
        b = prime_count(b);
        res = calc(n, a) + ((1LL * (b + a - 2) * (b - a + 1)) >> 1);

        for(int i = a; i < b; i++){
            w = n / primes[i];
            int lim = prime_count(sqrt(w)); 
            res -= prime_count(w);
            
            if(i <= c) for(int j = i; j < lim; j++)
                res += j - prime_count(w / primes[j]);
        }
        return res;
    }
} prime_count;

int main() {
    
    FastIO();
    long long n; cin >> n;
    cout << prime_count(n) << '\n';

    return 0;
}
 
void FastIO(){ios_base::sync_with_stdio(0);cin.tie(0);cout.tie(0);}
template<typename T> void prd(const T& x){cerr<<x;}
template<typename T, typename U>void prd(const pair<T, U>& val){cerr<<"(";prd(val.fi);cerr<<", ";prd(val.se);cerr<<")";}
template<typename T, typename... Args>void prd(const T& val, Args... args){prd(val);cerr<<", ";prd(args...);}
template<typename... Args> void debug(Args... args){cerr << "["; prd(args...);cerr<<"]\n";}
template<typename T> void debug(const set<T>& c){cerr<<'[';bool cm=0;for(const auto& st:c){if(cm)cerr<<", ";prd(st);cm=1;}cerr<<"]\n";}
template<typename T> void debug(const vector<T>& c){cerr<<'[';bool cm=0;for(const auto& v:c){if(cm)cerr<<", ";prd(v);cm=1;}cerr<<"]\n";}
template<typename T> void debug(const vector<vector<T>> &c){for(const auto &v: c)debug(v);cerr<<'\n';}
template<typename K, typename V> void debug(const map<K, V>& c){cerr<<'[';bool cm=0;for(auto[k, v]:c){if(cm)cerr<<", ";cerr<<'[';prd(k);cerr <<", ";prd(v);cerr<<']';cm = 1;}cerr<<"]\n";}
